Naive Bayes Case Study

In [1]:
import numpy as np
import pandas as pd 
import sklearn

In [2]:
# Option 1: Use double backslashes otherwise the paths wont be proper
docs = pd.read_csv("C:\\Users\\devth\\Documents\\VScode files\\Machine learning\\Bayes_casestu\\example_train1.csv")
# text in colomnn 1 and classfier in colomn 2
docs

Document      Class
0         Teclov is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [3]:
# converting the label to numerical values
docs['Class'] = docs.Class.map({'cinema':0,'education':1})
docs

Document  Class
0         Teclov is a great educational institution.      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [4]:
# converring the colomns into an array format each 
numpy_array = docs.to_numpy()
X = numpy_array[:,0]
Y = numpy_array[:,1] # the first one chooses the entire row and the second condition gives the number of colomns 

Y=Y.astype("int") 

print('X')
print(X)
print('Y')
print(Y)


X
['Teclov is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
Y
[1 1 1 0 0]


In [5]:
''' we have to now break down x into individual words and make a dictionary of unique words in the set This is called vectorization of words we have a function in skikit that enbles us to do the same 

create an object of CountVectorization() class '''


from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()


# used to convert it to a vector format

In [6]:
# here vec is an object of class CountVectorizer. This has a method called fit() which converts a corpus of documents into vector of unique words as shown below 

vec.fit(X)
vec.vocabulary_
# the results show that the distinct words and how many times they occur in the output as a dictionary key value pair

{'teclov': 15,
 'is': 9,
 'great': 6,
 'educational': 3,
 'institution': 8,
 'greatness': 7,
 'depends': 2,
 'on': 12,
 'ethics': 4,
 'story': 14,
 'of': 11,
 'and': 0,
 'sholey': 13,
 'cinema': 1,
 'good': 5,
 'movie': 10}

In [18]:
# stop words 
''' we can see a few trivial words like 'the', 'is', 'a' etc. which are not useful for our analysis. We can remove these words using the stop_words parameter of the CountVectorizer class.
it can be initialized as follows:'''

# removing the stop words
vec = CountVectorizer(stop_words='english')
vec.fit(X)
vec.vocabulary_

{'teclov': 11,
 'great': 5,
 'educational': 2,
 'institution': 7,
 'greatness': 6,
 'depends': 1,
 'ethics': 3,
 'story': 10,
 'sholey': 9,
 'cinema': 0,
 'good': 4,
 'movie': 8}

In [9]:
# another way of prnting the vocabulary
print(vec.get_feature_names_out())
print(len(vec.get_feature_names_out())) # this will give the number of unique words in the corpus

['cinema' 'depends' 'educational' 'ethics' 'good' 'great' 'greatness'
 'institution' 'movie' 'sholey' 'story' 'teclov']
12


In [19]:
# so now to do classification we must represent all the documents with respec to these words in the form of features
# every document will be converted to a feature vector representing presence of each of these words in the document. 
# lets convert each of our training documents in to a feature vector

X_transformed = vec.transform(X)
X_transformed
#print(X_transformed)

<5x12 sparse matrix of type '<class 'numpy.int64'>'
	with 20 stored elements in Compressed Sparse Row format>

We can see X_transformed is a 5x12 matrix. It has 5 rows for each of our 5 documents and 12 colomns each of one word of the dictionary which we just created. Let us print X_transformed

In [22]:
print(X_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 7)	1
  (0, 11)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 6)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 6)	1
  (2, 10)	1
  (3, 0)	1
  (3, 5)	1
  (3, 9)	1
  (4, 1)	1
  (4, 4)	2
  (4, 8)	1
  (4, 10)	1


In [ ]:
'''since X is converted into an array so we can just print to see it 
5 rows 12 colomns and each word that we have has been marked in it'''
print(X)

[[0 0 1 0 0 1 0 1 0 0 0 1]
 [0 1 1 1 0 0 1 0 0 0 0 0]
 [0 0 1 1 0 1 1 0 0 0 1 0]
 [1 0 0 0 0 1 0 0 0 1 0 0]
 [0 1 0 0 2 0 0 0 1 0 1 0]]


In [ ]:
# to make a better representation of the data set we can convert it into a data from 

'''the way to covert the matrix to a data frame is as follows: 
pd.DataFrame(matrix,colomns=colomns)'''

pd.DataFrame(X,columns=vec.get_feature_names_out())

cinema  depends  educational  ethics  good  great  greatness  institution  \
0       0        0            1       0     0      1          0            1   
1       0        1            1       1     0      0          1            0   
2       0        0            1       1     0      1          1            0   
3       1        0            0       0     0      1          0            0   
4       0        1            0       0     2      0          0            0   

   movie  sholey  story  teclov  
0      0       0      0       1  
1      0       0      0       0  
2      0       0      1       0  
3      0       1      0       0  
4      1       0      1       0

We call vectorzation the general process of turning a collection of text in a document into numerical feature vectors. This specific strategy is called the " Bag of Words " representation. Documents are described by word occurencies while completely ignoring the relative position information of the words in the documents.

The 4 steps to vectorization are as follows: 

1- import 
2- Instantiate 
3- Fit 
4- Transform 

In [35]:
test_docs = pd.read_csv("C:\\Users\\devth\\Documents\\VScode files\\Machine learning\\Bayes_casestu\\example_test.csv")
test_docs

Document      Class
0  very good educational institution.  education

In [37]:
# convert the labels into numerical variables 

test_docs['Class'] = test_docs.Class.map({'cinema':0,'education':1})
test_docs

Document  Class
0  very good educational institution.      1

In [49]:
test_numpy_array = test_docs.to_numpy()
test_numpy_array


array([['very good educational institution.', 1]], dtype=object)

In [46]:
X_test = test_numpy_array[:,0]
y_test = test_numpy_array[:,1]
y_test = y_test.astype('int')
print('X_test:', X_test)
print('y_test:', y_test)

X_test: ['very good educational institution.']
y_test: [1]


In [50]:
# converitng to the vectorized matrix 
X_test_transformed = vec.transform(X_test)
print(X_test_transformed)

  (0, 2)	1
  (0, 4)	1
  (0, 7)	1


In [51]:
X_test = X_test_transformed.toarray()
print(X_test)

[[0 0 1 0 1 0 0 1 0 0 0 0]]


*** Multinomial Naie Bayes***

In [52]:
# nuilding multinomial NB model 
from sklearn.naive_bayes import MultinomialNB

# instantiating NB class
mnb = MultinomialNB()

# fitting the model on training data 

mnb.fit(X,Y)

# predicting the labels for test data
mnb.predict_proba(X_test)

array([[0.32808399, 0.67191601]])

In [ ]:
proba = mnb.predict_proba(X_test) # returns the probability of the sentences beloning to a certain class
print("probability of test document beloning to class CINEMA: ",proba[0][0])    
print("probability of test document beloning to class EDUCATION: ",proba[0][1])

probability of test document beloning to class CINEMA:  0.32808398950131207
probability of test document beloning to class EDUCATION:  0.671916010498688


*** Bernoulli Naive Bayes ***

In [55]:
from sklearn.naive_bayes import BernoulliNB
# instatntiating bernoulliNB class
bnb = BernoulliNB()
# fitting the model on training data
bnb.fit(X,Y)
# predicting the labels for test data
y_pred = bnb.predict(X_test)
proba = bnb.predict_proba(X_test) # returns the probability of the sentences beloning to a certain class
print("probability of test document beloning to class CINEMA: ",proba[0][0])
print("probability of test document beloning to class EDUCATION: ",proba[0][1])

probability of test document beloning to class CINEMA:  0.23263740486986176
probability of test document beloning to class EDUCATION:  0.7673625951301384
